[project]
name = "stx-crop-chain-ledger"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/stx-crop-chain-ledger/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stx-crop-chain-ledger]
path = "contracts/stx-crop-chain-ledger.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
